### ISSUE TITLE
CORS cookie required for API invocation

### ISSUE THREAD

**Issue by JonDavis-AZED** [AmbitGroupvienna/usda-fns-ingest#32]
POSTing to the API fails without a CORS cookie results in an error. I work around it doing an OPTIONS call as text/html. This is not the optimal solution as we are not querying from a UI / HTML, but at least OPTIONS (vs GET) eliminates the payload which we'd otherwise throw away.

Also, none of this is documented. Suggest implementing an alternate solution for pseudo-security for API calls rather than CORS.

**Comment by JonDavis-AZED** [comment]
We see 401 "Authentication credentials were not provided" now but don't know what to do from here.

**Comment by amymok** [comment]
@JonDavis-AZED did you get the credential from @EHarper-OPI?

Let us know if #45 fixes this issue for you.

**Comment by JonDavis-AZED** [comment]
Yes we did, thank you. We now have

    Authorization: Token {TOKEN}

Instead of a 401 we received a 200 ~~with a new validation failure (isvalid = false) with the original "valid" sample, but I have yet to diagnose this and would be a separate issue~~ (with an error on our side where we had an extra field mapped in).

**Comment by amymok** [comment]
@JonDavis-AZED  Oh okay, so this works without you using OPTIONS?  You are now using POST?  I want to see if #45 fixed the issue for you.  If so, I can merge the PR into master branch and put that up to staging and production.

cc: @tadhg-ohiggins

**Comment by JonDavis-AZED** [comment]
Yes, it worked with the OPTIONS call removed and using only POST. Thanks!
